@jwt = eyJhbGciOiJIUzI1NiJ9.MQ.gTK3JhYZ5DqbORiRPjVDEPFANoCBGLOPpvTSqdjxyAU

#############
### TODOS ###
#############

### INDEX
GET http://localhost:3000/todos 
Authorization: Bearer {{jwt}}

### SHOW
GET http://localhost:3000/todos/5

### CREATE
POST http://localhost:3000/todos
Content-Type: application/json

{
  "description": "Get a new job"
}

### UPDATE
PATCH http://localhost:3000/todos/3
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "completed": 1
}

### DELETE
DELETE http://localhost:3000/todos/1
Authorization: Bearer {{jwt}}

