@jwt = eyJhbGciOiJIUzI1NiJ9.MQ.F0BNFoIruX9-qETBu_qG_JJpxUVco4uSIBLM29_Myj4


#############
### USERS ###
#############

### INDEX
GET http://localhost:3000/users 
Authorization: Bearer {{jwt}}

### SHOW
GET http://localhost:3000/users/1
Authorization: Bearer {{jwt}}

### CREATE
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "brandon",
  "password": "password"
}

### SELF
GET http://localhost:3000/users/me
Authorization: Bearer {{jwt}}

### UPDATE
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "completed": 1
}

### DELETE
DELETE http://localhost:3000/users/2
